name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Validate Supabase env
        run: |
          if [ -z "$VITE_SUPABASE_URL" ]; then echo "❌ Missing VITE_SUPABASE_URL secret" && exit 1; fi
          if [ -z "$VITE_SUPABASE_ANON_KEY" ]; then echo "❌ Missing VITE_SUPABASE_ANON_KEY secret" && exit 1; fi
      - name: Build (GitHub Pages base)
        run: npm run build:pages
        env:
          GITHUB_PAGES: '1'
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      - name: Add SPA fallback (404.html)
        run: cp dist/index.html dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
