name: Vercel Deploy

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Allow either GitHub Secrets or Repository Variables to provide the hook URLs
      VERCEL_DEPLOY_HOOK_PROD: ${{ secrets.VERCEL_DEPLOY_HOOK_PROD || vars.VERCEL_DEPLOY_HOOK_PROD || 'https://api.vercel.com/v1/integrations/deploy/prj_fw6cVFq4ZPs2LR7gtHxosh2wESEl/Q2WRf03X3W' }}
      VERCEL_DEPLOY_HOOK_PREVIEW: ${{ secrets.VERCEL_DEPLOY_HOOK_PREVIEW || vars.VERCEL_DEPLOY_HOOK_PREVIEW || 'https://api.vercel.com/v1/integrations/deploy/prj_fw6cVFq4ZPs2LR7gtHxosh2wESEl/Q2WRf03X3W' }}
    steps:
      - name: Trigger production deploy (main)
        if: github.ref == 'refs/heads/main' && env.VERCEL_DEPLOY_HOOK_PROD != ''
        run: |
          echo "Triggering Vercel production deploy via hook"
          curl -sS -X POST "$VERCEL_DEPLOY_HOOK_PROD" || exit 1

      - name: Trigger preview deploy (non-main)
        if: github.ref != 'refs/heads/main' && env.VERCEL_DEPLOY_HOOK_PREVIEW != ''
        run: |
          echo "Triggering Vercel preview deploy via hook for $GITHUB_REF_NAME"
          curl -sS -X POST "$VERCEL_DEPLOY_HOOK_PREVIEW" || exit 1

      - name: No deploy hook configured
        if: env.VERCEL_DEPLOY_HOOK_PROD == '' && env.VERCEL_DEPLOY_HOOK_PREVIEW == ''
        run: |
          echo "No Vercel deploy hooks set. Add secrets VERCEL_DEPLOY_HOOK_PROD and/or VERCEL_DEPLOY_HOOK_PREVIEW to enable automatic deploys."
